create table client_bank (id bigint generated by default as identity (start with 1),
                            email varchar(50) unique ,
                            first_name varchar(50),
                            last_name varchar(50),
                            primary key (id));